trigger:
  branches:
    include:
      - refs/tags/*
      - "master"
stages:
  - stage: Build
    jobs:
      - job:
        strategy:
          matrix:
            windows:
              imageName: 'windows-2019'
              rid: "win-x64"
              PLATFORMLINKER: ""
              ExE_FILE_ExT: ".exe"
        pool:
          vmImage: $(imageName)

        steps:
          - script: |
              sudo apt-get update
              sudo apt-get install -y libkrb5-dev
            condition: "eq(variables['imageName'],'ubuntu-16.04')"
            name: "install_packages"
          - task: DotNetCoreCLI@2
            name: "restore_solution"
            displayName: "restoring solution"
            inputs:
              command: 'restore'
              projects: "dotnet-anv.sln"
          - task: DotNetCoreCLI@2
            name: "build_solution"
            inputs:
              command: "build"
              configuration: "release"
              projects: "dotnet-anv.sln"
          - task: DotNetCoreCLI@2
            name: "test_solution"
            inputs:
              command: "test"
              configuration: "Release"
              projects: "dotnet-anv.sln"
          - task: DotNetCoreCLI@2
            name: "pack_solution"
            inputs:
              command: "pack"
              configuration: "release"
              packagesToPack: "dotnet-ansible-vault-decoder/dotnet-ansible-vault-decoder.csproj"
          - task: DotNetCoreCLI@2
            name: "publish_project"
            inputs:
              command: "custom"
              custom: "publish"
              arguments: "-c Release"
              projects: "dotnet-ansible-vault-decoder/dotnet-ansible-vault-decoder.csproj"
              publishWebProjects: false
          - task: CopyFiles@2
            name: "copying_nupkg"
            inputs:
              sourceFolder: "dotnet-ansible-vault-decoder/bin/Release"
              contents: "**/*.nupkg"
              targetFolder: "$(Build.ArtifactStagingDirectory)"
          - task: PublishBuildArtifacts@1
            name: "publishing_artifacts"
            inputs:
              pathToPublish: "$(Build.ArtifactStagingDirectory)"
              artifactName: "dotnet-anv-$(rid)"
  - stage: Release
    condition: "startsWith(variables['Build.SourceBranch'], 'refs/tags/')"
    jobs:
      - job:
        displayName: "Github Release"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: download win-x64
            inputs:
              artifact: dotnet-anv-win-x64
              path: "$(Build.ArtifactStagingDirectory)"
          - task: GitHubRelease@0
            displayName: "releasing github"
            inputs:
              gitHubConnection: "dotnet-ansible-vault-decoder"
              action: create
              target: "$(Build.SourceVersion)"
              assets: "$(Build.ArtifactStagingDirectory)/*"
              isDraft: true

